version: '3.8'
services:
  app-dev:
    image: evanmclean/secure-authentication:dev-v1.0
    build:
      context: .
      target: development
    environment:
      - NODE_ENV=development
      - MONGODB_URI=${MONGODB_URI}
    volumes:
      - .:/usr/src/app
    ports:
      - "8881:8881"
    command: ["npm", "run", "dev"]
    networks:
      - app-network
    env_file:
      - .env
  app-prod:
    image: evanmclean/secure-authentication:prod-v1.0
    build:
      context: .
      target: production
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
    ports:
      - "80:8881"
    command: ["npm", "run", "start"]
    networks:
      - app-network
    env_file:
      - .env
  app-test:
    image: evanmclean/secure-authentication:test-v1.0
    build:
      context: .
      target: testing
    environment:
      - NODE_ENV=test
      - MONGODB_URI=${MONGODB_URI}
    volumes:
      - .:/usr/src/app
    command: ["npm", "run", "test"]
    networks:
      - app-network
    env_file:
      - .env
networks:
  app-network:
    driver: bridge