name: Docker Compose CI/CD
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23"
      - name: Install dependencies
        run: npm install
      - name: Create .env file
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > .env
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose
      - name: Run tests
        run: |
          docker-compose -f docker-compose.yaml up -d app-test
          docker-compose -f docker-compose.yaml logs app-test
          docker wait $(docker-compose -f docker-compose.yaml ps -q app-test)
      - name: Build Docker images
        run: docker-compose -f docker-compose.yaml build
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker images
        run: |
          docker push evan/secure-authentication:dev-v1.0
          docker push evan/secure-authentication:prod-v1.0
          docker push evan/secure-authentication:test-v1.0
      - name: Shut down Docker Compose
        run: docker-compose -f docker-compose.yaml down
